### PR TITLE
Use Material UI Elements

### PR DESCRIPTION
**Pull request by christophwitzko**
Hi @takanabe,

thank you for this awesome boilerplate.
I have replaced the standard HTML elements with some better styled Material UI Components. I hope you like that change.

Have a great day,
Christoph

screen shot 2016-01-04 at 23 08 40

### CODE REVIEW

**Comment by takanabe** [comment]
@christophwitzko 
Hi ! I am happy to hear that you are into the boilerplate :)

of cource, I wanna merge your great commits. But I could not access the page you share with photo.
The error message is like follows:

```
Uncaught TypeError: ColorManipulator.fade is not a function
```

Did you try `git clone` , `npm install`, `npm start` from first after changing codes as shown in README.md ?

**Comment by christophwitzko** [comment]
Oops, looks like webpack caching is a little bit too awesome. :grin: 
Commit b741c11 should fix it.

**Comment by takanabe** [comment]
@christophwitzko 

Thanks to fix ! 
Then please  rebase commit `b741c1148` & `5f157e61` and push again please :D

**Comment by christophwitzko** [comment]
@takanabe Done!

**Comment by takanabe** [comment]
@christophwitzko 

Merged !
Danke :)

**Pull request merged**
