### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jakeboone02**
Thanks for this boilerplate repo.  I used it for my latest project and it was a great starting point.  I just updated the dependencies in said project so I thought I'd return the favor and update this repo.

For Babel 6, I replaced invalid loader config options with presets and plugins in a new `.babelrc` file.

I had to make another modification to get it to build on my system.  The `context` field in `webpack.config.js` is now just `__dirname`, and each `entry` point now includes the `./src` part of the path.

I was going to update `react` to `15.0.1`, but the `material-ui` version that includes React 15 compatibility is still in [beta](https://github.com/callemall/material-ui/releases/tag/v0.15.0-beta.1).  Maybe in a few more weeks.

### CODE REVIEW

**Comment by jakeboone02** [comment]
The app isn't working as expected so let me clear that up first.

**Comment by takanabe** [comment]
Thank you for giving me a feedback. I know that version dependencies of React, Redux and Material UI is very strict and it's always irritating me. 

So if you fix the problems, please send me PR again!

**Comment by jakeboone02** [comment]
I fixed the issue with the app.  It had to do with `react-tap-event-plugin` only working with React 15.  Had to revert to an earlier version.  Also added compatibility with Redux Dev Tools extension.

When `material-ui@0.15.0` is released, you can update to React 15 and `react-tap-event-plugin@^1.0.0`.

**Comment by jakeboone02** [comment]
Squashed to a single commit.

**Comment by takanabe** [comment]
I really appreciate the package update because I didn' do that. Furthermore, your feedbacks are variable for me especially about dependencies of material-ui@0.15, React 15, and `react-tap-event-pluging@1.0.0`. 

Anyway, thank you for your great PR!

**Comment by jakeboone02** [comment]
You're welcome!  You help me, I help you...that's how this works, right?  :)

**Pull request merged**
