### PR TITLE
Updated Packages

### PR DESCRIPTION
**Pull request by lipho**
Updated a few packages. Kept react-hot-loader at 1.3.0 because the current beta 3.0 doesn't support hot reloading as of yet.

### CODE REVIEW

**Comment by takanabe** [comment]
@lipho  Thank you for updating ! I will merge this PR :D

I guess that we `.idea` is not necessary for the boilerplate,  right ?

**Comment by lipho** [comment]
No not necessary. Just IDE settings. Thank you.

**Comment by takanabe** [comment]
@lipho , Please discard .idea from your PR

**Comment by lipho** [comment]
@takanabe Done. Thank you.

**Comment by takanabe** [comment]
@lipho  Thanks! one more thing. Could  you squash your commits into one ?

**Comment by lipho** [comment]
@takanabe All done 😄

**Comment by takanabe** [comment]
thank you!

**Pull request merged**
